kind: Job
apiVersion: batch/v1
metadata:
  name: nginx-job
  namespace: nginx
spec:
  completions: 1
  parallelism: 1
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx-job
    spec:
      containers:
      - name: nginx-container
        image: busybox:latest
        command: ["sh","-c","echo Nginx Jobs start! && sleep 10"]
      restartPolicy: Never    

  
